blank_issues_enabled: false
contact_links:
    - name: Ask a Question
      url: https://github.com/IgniteUI/igniteui-react/discussions/new
      about: Start a Discussion.
    - name: Read the Docs
      url: https://www.infragistics.com/products/ignite-ui-react/react/components/general-getting-started
      about: Be sure you've read the docs!
